export const EXCHANGE_RATES_REQUEST = 'EXCHANGE_RATES_REQUEST'
export const EXCHANGE_RATES_SUCCESS = 'EXCHANGE_RATES_SUCCESS'
export const EXCHANGE_RATES_FAILURE = 'EXCHANGE_RATES_FAILURE'

export const LOWEST_RATES_REQUEST = 'LOWEST_RATES_REQUEST'
export const LOWEST_RATES_SUCCESS = 'LOWEST_RATES_SUCCESS'
export const LOWEST_RATES_FAILURE = 'LOWEST_RATES_FAILURE'

export const HISTORICAL_PRICING_REQUEST = 'HISTORICAL_PRICING_REQUEST'
export const HISTORICAL_PRICING_SUCCESS = 'HISTORICAL_PRICING_SUCCESS'
export const HISTORICAL_PRICING_FAILURE = 'HISTORICAL_PRICING_FAILURE'
export const HISTORICAL_PRICING_FILTER_SELECTED = 'HISTORICAL_PRICING_FILTER_SELECTED'
